# PostgreSQL database configuration

connection: &connection
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: 
  timeout: 5000

development:
  <<: *connection
  database: vaanam_development

test:
  <<: *connection
  database: vaanam_test
